/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    KeyValue: typeof import('./components/key-value.vue')['default']
    LoadingError: typeof import('./components/loading-error.vue')['default']
    RatingFilter: typeof import('./components/rating-filter.vue')['default']
    RestaurantCard: typeof import('./components/restaurant/card.vue')['default']
    RestaurantLocation: typeof import('./components/restaurant/location.vue')['default']
    RestaurantReview: typeof import('./components/restaurant/review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
